facebook/php-graph-sdk

- docs/FacebookResponseException.fbmd
- docs/sdk_reference.fbmd
- src/Facebook/Exceptions/FacebookAuthenticationException.php
- src/Facebook/Exceptions/FacebookResponseException.php
- tests/Exceptions/FacebookResponseExceptionTest.php
How we don't see this before???
All current ``FacebookAuthorizationException`` are in fact authentication exceptions!
I also rename ``FacebookPermissionException`` to ``FacebookAuthorizationException`` because security is often authentication and authorization.
> Fix auth exceptions

- src/Facebook/Entities/AccessToken.php
- src/Facebook/FacebookRedirectLoginHelper.php
- tests/FacebookRedirectLoginHelperTest.php
Using getLogoutUrl with an app session can leak the appSecret.
> Prevent generation of logout url with app session.

- src/Facebook/HttpClients/FacebookCurl.php
This adds a null initiator to $curl property of FacebookCurl and a check in the init method so previously created handlers aren't stepped on.
> Curl handler check

- docs/sdk_getting_started.fbmd
The constructor is :
public function __construct($redirectUrl, $appId = null, $appSecret = null)
The first param $redirectUrl is therefore mandatory.
> Add mandatory param to the RedirectLoginHelper constructor

- .travis.yml
- Use `before_install` and `install`
- Remove deprecated composer `--dev` option
- Use the required PHPUnit to run tests
> Better Travis-CI

- src/Facebook/GraphNodes/GraphAchievement.php
- src/Facebook/GraphNodes/GraphApplication.php
- src/Facebook/GraphNodes/GraphObject.php
- src/Facebook/GraphNodes/GraphObjectFactory.php
- tests/GraphNodes/GraphAchievementTest.php
- tests/GraphNodes/GraphNodeTest.php
In an effort to add approachable classes and objects to the library, and prompted by a laundry list item in https://github.com/SammyK/facebook-php-sdk-v4/issues/1, I have added a node class for "achievement" 
https://developers.facebook.com/docs/graph-api/reference/v2.2/achievement
This is my first contribution adding Node classes like this, I would like to know if there are any specific aspects of this implementation that should be refined before moving forward with adding additional classes.
I also created bare-bones class for the "application" node. This will need more energy later.
Finally, I created a base abstract `GraphNodeTest ` to be used to move some code repetition away from the individual Node test classes.
> Adding GraphAchievement Node class

- src/Facebook/GraphUser.php
Since 'timezone' is considered a core element of the User object (and I need it) I've included it in GraphUser
> getTimezone for GraphUser

- src/Facebook/PseudoRandomString/OpenSslPseudoRandomStringGenerator.php
This was causing the tests to fail. You can't concatenate string on a constant.
Now that we have Travis CI, we should make sure the tests are passing before merging in a PR. :)
> Fix for invalid PHP syntax

- src/Facebook/HttpClients/FacebookCurl.php
- src/Facebook/HttpClients/FacebookCurlHttpClient.php
The curl handle wasn’t cleared after closing, and due to this commit eb747316e313944a06b9129e51c58f5bfda2ef2d it wasn’t initialized again.
I also changed the `FacebookCurlHttpClient::$facebookCurl` field to be non-static (since every client has needs it’s own handle)
> clear the curl handle after closing it

- src/Facebook/FacebookRequest.php
for some reason, the new v4 SDK dropped support for the different API sub domains... which meant that video publishing would use the main api rather than the graph-video subdomain.
This minor fix introduces a change to support the video url.
> added support for graph-video url

- src/Facebook/Entities/AccessToken.php
- src/Facebook/Entities/SignedRequest.php
- src/Facebook/FacebookRedirectLoginHelper.php
- src/Facebook/FacebookRequest.php
- src/Facebook/FacebookRequestException.php
- src/Facebook/FacebookSignedRequestFromInputHelper.php
- src/Facebook/HttpClients/FacebookCurl.php
- src/Facebook/HttpClients/FacebookCurlHttpClient.php
- src/Facebook/HttpClients/FacebookGuzzleHttpClient.php
- src/Facebook/HttpClients/FacebookHttpable.php
- src/Facebook/HttpClients/FacebookStreamHttpClient.php
Code cleanup (actually code base is in very good state): code style, if conditionals, strict types, performance. Tests are green.
Following tools are used for code analysis: PhpStorm + <a href="https://plugins.jetbrains.com/plugin/7622?pr=phpStorm">Php Inspections (EA Extended)</a>.
> Static Code Analysis warnings fixed (partially)

- CONTRIBUTING.md
- README.md
- composer.json
Hey @gfosco! In preparation for [Chi PHP UG's open source workshop](http://www.meetup.com/Chicago-PHP-User-Group/events/219902483/) tomorrow, I've added the Code Sniffer dev dependency as a way to check files for PSR-2 before committing them. And I added some more instructions to the CONTRIBUTING file. :)
PS: I'm working hard on the docs as well. I'm about 50% done. :)
> Add PHP CodeSniffer and CONTRIBUTION instructions

- src/Facebook/autoload.php
The extra ```\``` is causing the ```strncmp``` check to fail, resulting in Fatal Errors.
> Fixed auto-load prefix

- src/Facebook/HttpClients/FacebookCurlHttpClient.php
- src/Facebook/HttpClients/FacebookGuzzleHttpClient.php
- src/Facebook/HttpClients/FacebookHttpable.php
- src/Facebook/HttpClients/FacebookStreamHttpClient.php
You made a breaking change to an interface in a minor patch library fix (`4.0.16` → `4.0.17`). This fucks up any library implementing this interface. According to [semantic versioning](http://semver.org) this should be a major version bump, so I suggest reverting this change.
> revert interface change

- src/Facebook/FacebookRedirectLoginHelper.php
After updating to 4.0.19, the isValidRedirect function didn't work right. The wrong variables were checked against each other.
> fix: validate state

- src/Facebook/PseudoRandomString/UrandomPseudoRandomStringGenerator.php
The `stream_set_read_buffer()` function is [not supported on HHVM](http://docs.hhvm.com/manual/en/function.stream-set-read-buffer.php) and is causing the [tests to fail on Travis-CI](https://travis-ci.org/facebook/facebook-php-sdk-v4/jobs/52794560#L180). This is the fix. :)
> [4.1] Fix HHVM bug

- .travis.yml
- Added Travis-CI check for PHP 7.0 since that's [gonna be thing soon](https://wiki.php.net/rfc/php7timeline#proposal). I've got `allow_failures` on so it won't cause the whole build to fail.
- Removed `allow_failures` for HHVM (because hey - you're Facebook and your PHP SDK should run on your flavor of PHP!) :P
- Added `travis_retry` wrapper to `composer` commands so that it'll [retry on timeouts](http://docs.travis-ci.com/user/build-timeouts/).
> [4.1] Add Travis-CI check for PHP 7.0 & other changes

- docs/Facebook.fbmd
- src/Facebook/Facebook.php
The Graph API supports parameters for DELETE Requests.
For example: Unblocking a user from a page requires a parameter "user"
which the current version of the SDK doesn't implement.
Docs were updated also.
> Updated delete method to support parameters - #379

- src/Facebook/FacebookPermissions.php
For the comfort a final class holding all permissions as a constant for easier usage.
> Add a final class holding all permissions

- src/Facebook/HttpClients/FacebookCurlHttpClient.php
- tests/HttpClients/FacebookCurlHttpClientTest.php
I went in to debug #383 and found that the 4.0 tests were failing out of the box. This PR:
1. Fixes the tests.
2. Removes the PUT test as PUT is not supported by the Graph API.
3. Adds support for multidimensional params and a multidimensional param test.
This is just a hack to get multidimensional param support without rewriting all the HTTP client stuffs like we did in 4.1. :)
> [4.0] Fix for multidimensional params support

- src/Facebook/Facebook.php
Bumps fallback Graph version to v2.3.
Going to be proposing removing this fallback completely in v4.2 and throwing an error if the `default_graph_version` option is not supplied. :)
> [4.1] Graph version bump to v2.3

- src/Facebook/autoload.php
These both work the same
``` php
define('FACEBOOK_SDK_V4_SRC_DIR', 'path/to/Facebook/');
// OR
define('FACEBOOK_SDK_V4_SRC_DIR', 'path/to/Facebook');
```
> Support setting base directory with or without the trailing slash

- src/Facebook/Http/RequestBodyMultipart.php
- tests/Http/RequestBodyMultipartTest.php
- tests/Http/RequestUrlEncodedTest.php
Inspired by #383, I went in to add tests to 4.1 to show it had multidimensional-arrays-to-nested-params support and it did for `application/x-www-form-urlencoded` requests, but not `multipart/form-data` requests.
This is an important feature since you might want to target an audience for a video on a page post for example:
```php
$fb = new Facebook\Facebook([/* . . . */]);
$data = [
'title' => 'Foo Video',
'description' => 'My foo video.',
'source' => $fb->videoToUpload('/path/to/video.mp4'),
'targeting' => [
'countries' => 'US,GB',
'age_min' => 13,
],
];
$response = $fb->post('/{some-page-id}/videos', $data, '{page-access-token}');
```
Before this PR, PHP would poop out an error:
Notice: Array to string conversion in /path/to/facebook-php-sdk-v4/src/Facebook/Http/RequestBodyMultipart.php …
> [4.1][Fix] Add support for nested params for multipart requests

- src/Facebook/FacebookRedirectLoginHelper.php
In Graph `v2.2` and below, GET requests to the `/oauth/access_token` endpoint would return a query string in the body of the response:
```
access_token=foo_token&expires=5183759
```
Starting in Graph `v2.3`, the response body is json:
```
{"access_token":"foo_token","token_type":"bearer","expires_in":5183686}
```
Since v4.0 of the PHP SDK translated these two responses differently, it was causing errors for anyone using Graph v2.3 (#391, #392 and even [here](https://github.com/SammyK/LaravelFacebookSdk/issues/56)). This PR is an ugly hack to fix this without BC's. :)
Not sure if this response change will affect any other places in 4.0, but if we get any more issues about `stdClass` errors, you can bet it's due to the Graph response change.
Version 4.1 of the SDK is unaffected.
> [4.0][Fix] Fix stdClass error on FacebookRedirectLoginHelper

- .scrutinizer.yml
Just realized that we don't have scrutinizer configured to check for PSR-2 which is why #405 is passing even though it's got PSR-2 violations in it. I *think* this PR will force PSR-2 checks on scrutinizer's end. :)
> Add scrutinizer config for PSR-2 checks

- README.md
Since the `4.1-dev` branch is not going to reflect `master` anymore, we can update the badges. The Scrutinizer one doesn't work for some reason.
> Update README badges for specific branch name

- src/Facebook/Facebook.php
- src/Facebook/autoload.php
- Deprecated `FACEBOOK_SDK_V4_SRC_DIR` for unversioned `FACEBOOK_SDK_SRC_DIR`
- Added a TODO note to force the `default_graph_version` option in v6
> Further prep for v5

- composer.json
This should add an alias for `~5.0@dev` on the master branch.
@yguedidi Can you ensure this + #417 will do what we've been discussing? :)
> Add branch alias for PHP SDK v5

- composer.json
This is a tandem PR with the one I'm about to submit on `master`.
@yguedidi Can you review this one and the one I'm about to submit to ensure this is going to not break the existing aliases and also enable `~5.0@dev`?
> Remove branch alias on 4.1-dev branch

- docs/GraphObject.fbmd
Was reading the docs and found this typo. Thought I'd send a PR.
> Fix `getExpiresAt` Typo.

- src/Facebook/GraphUser.php
> Added getLocale()

- src/Facebook/FacebookRequest.php
Fixed missing forward slash between version number and the rest of the URL.
> Missing Forwardslash

- src/Facebook/FacebookResponse.php
> Fix: No need for else branch as we're returning early

- src/Facebook/GraphNodes/GraphNodeFactory.php
> Fix: Method accepts only two arguments, not four

- CONTRIBUTING.md
-------
The current output of the code sniffer outputs this:
```
FILE: ...k-php-sdk-v4/src/Facebook/Authentication/AccessTokenMetadata.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
360 | WARNING | Line exceeds 120 characters; contains 128
|         | characters (Generic.Files.LineLength.TooLong)
----------------------------------------------------------------------
FILE: ...facebook-php-sdk-v4/src/Facebook/Authentication/OAuth2Client.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
146 | WARNING | Line …
```
> Add custom PHP_CodeSniffer rule set to ignore long line lengths

- README.md
- docs/FacebookApp.fbmd
I had to dig through the discussion in #382 before I found a link to @SammyK 's site where I was able to find the upgrade guide for v4.x to v5.x.
This pull request puts a link to the upgrade guide up-front in the Readme!
> Include link to upgrade guide in readme

- docs/FacebookApp.fbmd
- src/Facebook/Facebook.php
-The tag for this release is v5.1.0, but the `VERSION` constant still said `5.0.0`
-There are two typos in the documentation for FacebookApp
> Update SDK version and typo fix in FacebookApp

- src/Facebook/FacebookClient.php
The `FacebookCurlHttpClient` is using more than the `curl_init` function, so that class could be invoked without problems creating a fake `curl_init`: https://3v4l.org/CjcVS
> Check curl extension

- src/Facebook/GraphNodes/GraphEdge.php
- tests/FacebookTest.php
- tests/GraphNodes/GraphEdgeTest.php
Related with https://github.com/facebook/facebook-php-sdk-v4/issues/483
> Fix: Deep Pagination does not append extra parameters anymore

- src/Facebook/FacebookBatchResponse.php
- tests/FacebookBatchResponseTest.php
> Fix parsing of batch headers

- CHANGELOG.md
- src/Facebook/Facebook.php
- src/Facebook/HttpClients/HttpClientsFactory.php
- src/Facebook/PersistentData/PersistentDataFactory.php
- src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorFactory.php
- tests/FacebookTest.php
- tests/HttpClients/HttpClientsFactoryTest.php
- tests/PersistentData/PersistentDataFactoryTest.php
- tests/PseudoRandomString/PseudoRandomStringFactoryTest.php
To solve the `Facebook\Facebook` constructor complexity problem (defined on [Scrutinizer]()), I've splitted it into different factories:
* `Facebook\PseudoRandomString\PseudoRandomStringGeneratorFactory`
* `Facebook\HttpClients\HttpClientsFactory`
* `Facebook\PersistentData\PersistentDataFactory`
This should also allow you to move different detection logic into these factories and keeping some other classes' focus on their behaviour and responsabilities.
Another small change I did is the removal of an `\InvalidArgumentException` exception replicating a setter logic (afaik).
Of course I'll add related tests and documentation if the RFC is accepted.
> Complexity reduction

- src/Facebook/HttpClients/FacebookStream.php
- src/Facebook/HttpClients/FacebookStreamHttpClient.php
- src/Facebook/Url/FacebookUrlManipulator.php
* single internal type for response headers
* use the empty function instead of implicit casting
> headers type + empty function

- src/Facebook/GraphNodes/GraphObjectFactory.php
The method `makeGraphObject ` is marked as deprecated, so internally shouldn’t be used.
> replaced deprecated method

- src/Facebook/Authentication/OAuth2Client.php
- src/Facebook/FileUpload/FacebookResumableUploader.php
`Facebook\Authentication\AccessToken` is accepted by both `Facebook\Authentication\OAuth2Client` and `Facebook\FileUpload\FacebookResumableUploader` because implements the `__toString` method, but it wasn't added in the PHPDoc annotations.
> Fixed PHPDoc annotations

- src/Facebook/FacebookClient.php
- tests/FacebookClientTest.php
That commit fixes the access token validation bug, when access token is not being validated at all.
> [Bugfix] Facebook AccessToken is being validated correctly

- src/Facebook/HttpClients/HttpClientsFactory.php
Trying to initialize with `http_client_handler` set to `guzzle` without having Guzzle available (or `curl` without cURL) would result in a fatal error because there is no `Facebook\HttpClients\Exception` class:
```
PHP Fatal error:  Class 'Facebook\HttpClients\Exception' not found in ..../vendor/facebook/php-sdk-v4/src/Facebook/HttpClients/HttpClientsFactory.php on line 68
```
So I'd figure it should be a generic `Exception`.
> fix use of exception class

- README.md
We received a report that people are confused by the repo name. `facebook-php-sdk-v4` indicates that the repo is for v4, not v5 or other versions.
To make clear that people can find v5 in this repo the latest version number should be part of the headline.
> Added version number (v5) to headline

- src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorTrait.php
Added logic to wrap the extension missing fatal error and ensured the mb_filter function is taken from PHP base namespace and not from the FB SDK namespace.
Test running and succeeded:
```
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.
...............................................................  63 / 267 ( 23%)
............................................................... 126 / 267 ( 47%)
............................................................... 189 / 267 ( 70%)
............................................................... 252 / 267 ( 94%)
...............
Time: 6.36 seconds, Memory: 12.00Mb
OK (267 tests, 614 assertions)
```
> GitHub Issue #546: Received a fatal because mb_substr was not found.

- CHANGELOG.md
- src/Facebook/FacebookApp.php
Rewrites the serialization methods to use json_encode / json_decode to prevent Object Injection attacks.
See more: https://www.owasp.org/index.php/PHP_Object_Injection
This is also a request from WordPress to allow the SDK to be used in plugins on WordPress.com and WordPress VIP:
https://vip.wordpress.com/documentation/code-review-what-we-look-for/#serializing-data
> Avoids using unserialize to prevent Object Injection security issue.

- composer.json
- src/Facebook/Helpers/FacebookRedirectLoginHelper.php
- src/Facebook/HttpClients/FacebookCurlHttpClient.php
- src/Facebook/SignedRequest.php
- src/Facebook/polyfills.php
- tests/FacebookTest.php
- tests/HttpClients/FacebookCurlHttpClientTest.php
- tests/HttpClients/HttpClientsFactoryTest.php
- tests/PseudoRandomString/PseudoRandomStringFactoryTest.php
Re #546
This kills the unnecessary mb-string dependency. In doing so I was able to rip out quite a bit of code & tests related to the overly-complicated cURL client implementation. While ripping out mb-string for signed request signature validation, I made a polyfill for the [`hash_equals()` function](http://php.net/manual/en/function.hash-equals.php) in PHP 5.6 *(which has been [vetted by infosec nerds](https://twitter.com/SammyK/status/697179032983482368))*. This allowed me to removed the duplicate code for comparing the CSRF token for redirect logins as well as signed request signature validations.
Also - the tests were failing out of the box when mcrypt, openssl or curl weren't installed. I fixed all that. :)
Make sure to `composer dump-autoload` before reviewing this one. :)
> Remove mb-string dependency

- .travis.yml
- composer.json
The range operator isn't considered "safe" by Composer ([ref](https://getcomposer.org/doc/articles/versions.md#range)), so a switch to the caret operator is suggested.
Also the PHP 7 build ends with success, so imo it should be kept as a requirement also on TravisCI.
> Use Composer safe versions

- docs/Birthday.fbmd
- docs/GraphNode.fbmd
- docs/sdk_reference.fbmd
- src/Facebook/GraphNodes/Birthday.php
- src/Facebook/GraphNodes/GraphNode.php
- tests/GraphNodes/GraphUserTest.php
Fix for #570 since the Graph API can return the birthday field as either mm/dd/yyyy, mm/dd or yyyy.
> Implementing new Birthday class to handle Graph API response variations

- README.md
- docs/Facebook.fbmd
- docs/FacebookRequest.fbmd
- docs/example_access_token_from_canvas.fbmd
- docs/example_access_token_from_javascript.fbmd
- docs/example_access_token_from_page_tab.fbmd
- docs/example_batch_request.fbmd
- docs/example_batch_upload.fbmd
- docs/example_facebook_login.fbmd
- docs/example_pagination_basic.fbmd
- docs/example_post_links.fbmd
- docs/example_retrieve_user_profile.fbmd
- docs/example_upload_photo.fbmd
- docs/example_upload_video.fbmd
- docs/sdk_getting_started.fbmd
- src/Facebook/Facebook.php
[Graph v2.6](https://developers.facebook.com/docs/apps/changelog) is the new hotness. :)
> Bump Graph version to v2.6

- src/Facebook/FacebookApp.php
- tests/FacebookAppTest.php
Fixes #532 
Facebook app ID's are really big and on 32-bit systems many are bigger than `PHP_INT_MAX` causing integer overflow issues. We can't fix when people overflow an int:
```php
$appId = PHP_INT_MAX + 10;
```
But we can at least give them better error messages and prevent overflows when `FacebookApp` is unserialized. :)
> Add better error checking for app IDs as int when greater than PHP_INT_MAX

- tests/Authentication/OAuth2ClientTest.php
- tests/Exceptions/FacebookResponseExceptionTest.php
- tests/FacebookAppTest.php
- tests/FacebookBatchRequestTest.php
- tests/FacebookBatchResponseTest.php
- tests/FacebookClientTest.php
- tests/FacebookResponseTest.php
- tests/FileUpload/FacebookFileTest.php
- tests/FileUpload/FacebookResumableUploaderTest.php
- tests/GraphNodes/AbstractGraphNode.php
- tests/GraphNodes/GraphAlbumTest.php
- tests/GraphNodes/GraphEdgeTest.php
- tests/GraphNodes/GraphEventTest.php
- tests/GraphNodes/GraphGroupTest.php
- tests/GraphNodes/GraphNodeFactoryTest.php
- tests/GraphNodes/GraphObjectFactoryTest.php
- tests/GraphNodes/GraphPageTest.php
- tests/GraphNodes/GraphSessionInfoTest.php
- tests/GraphNodes/GraphUserTest.php
- tests/Helpers/FacebookCanvasHelperTest.php
- tests/Helpers/FacebookRedirectLoginHelperTest.php
- tests/Helpers/FacebookSignedRequestFromInputHelperTest.php
- tests/HttpClients/FacebookCurlHttpClientTest.php
- tests/HttpClients/FacebookGuzzleHttpClientTest.php
- tests/HttpClients/FacebookStreamHttpClientTest.php
- tests/SignedRequestTest.php
This PR
🙎 This is the visibility as declared on the parent; there's no need to increase it.
> Fix: Reduce visibility of setUp()

- tests/Authentication/OAuth2ClientTest.php
- tests/PseudoRandomString/PseudoRandomStringFactoryTest.php
- tests/bootstrap.php
> Fix: Remove unused imports

- tests/FacebookTest.php
- tests/FileUpload/FacebookResumableUploaderTest.php
- tests/PersistentData/FacebookSessionPersistentDataHandlerTest.php
This PR
💁 The variables are never actually assigned a value as during the evaluation of the expressions to the right, exceptions are thrown, so they can safely be removed, right?
> Fix: Remove unused local variables

- .travis.yml
This PR
💁 Ain't nobody got time for that, right?!
> Fix: Attempt to cache dependencies between builds

- src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorTrait.php
The method doesn't actually throw \InvalidArgumentException
> Corrected phpDoc comment for binToHex

- src/Facebook/Url/FacebookUrlDetectionHandler.php
Fixed a notice triggered on PHP 7.0+ Notice: Undefined variable: header, stacktraced in in facebook/php-sdk-v4/src/Facebook/Url/FacebookUrlDetectionHandler.php at line 98
> Fixed issue when Notice "Undefined variable: header" occured on PHP 7.0

- src/Facebook/Helpers/FacebookRedirectLoginHelper.php
When `FacebookRedirectLoginHelper::getLoginUrl()` is called it should first check if a CSRF token (called `state` in the source code) has already been generated and use the existing one if it has.
Right now any time the method is called, a new CSRF token is generated. That means if the method is called more than once, only the last URL will be working which is a problem.
What if the user opens up a webpage in multiple tabs at once? Then he will only be able to use Facebook login in the last tab. And if you forget to put favicon.ico on your website, then he will only be able to use Facebook login in IE :) (see https://github.com/facebook/facebook-php-sdk-v4/issues/583 for details).
> FacebookRedirectLoginHelper - let's not regenerate CSRF token

- src/Facebook/Helpers/FacebookRedirectLoginHelper.php
> Reset the CSRF so that it does not get reused

- src/Facebook/autoload.php
- src/Facebook/polyfills.php
- tests/FacebookTest.php
- tests/HttpClients/FacebookStreamHttpClientTest.php
Fixes #598
-> if composer isn't used, we need to include the polyfills manually
> fixed issue#598

- src/Facebook/FacebookBatchRequest.php
> Fix: Method does not return anything

- docs/AccessToken.fbmd
This PR fixes the documentation of the `AccessToken::isLongLived` method.
Related to #662.
> Fixed AccessToken::isLongLived documentation.

- src/Facebook/Http/GraphRawResponse.php
- tests/Http/GraphRawResponseTest.php
The raw response header field "X-FB-Ads-Insights-Throttle" contains a json value { "app_id_util_pct": 100, "acc_id_util_pct": 10 }
Calling $response->getHeaders()['x-fb-ads-insights-throttle'] results in a chopped value {"app_id_util_pct".
The fix will handle the transformation of the header fields in a valid way.
Similar to this fix:
https://github.com/facebook/facebook-php-ads-sdk/pull/241/files
Relates to https://github.com/facebook/php-graph-sdk/pull/678
> Fixed invalid format handling of headers[x-fb-ads-insights-throttle]

- composer.json
- src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorFactory.php
- src/Facebook/PseudoRandomString/RandomBytesPseudoRandomStringGenerator.php
- tests/FacebookTest.php
- tests/PseudoRandomString/PseudoRandomStringFactoryTest.php
- tests/PseudoRandomString/RandomBytesPseudoRandomStringGeneratorTest.php
Adds a check for PHP 7 CSPRNG first to keep mcrypt deprecation messages from appearing in PHP 7.1.
Addresses #663.
> Update CSPRNG factory

- .travis.yml
> Fix: Run build on PHP7.1

- src/Facebook/GraphNodes/GraphObjectFactory.php
This PR
💁‍♂️ The code is exactly the same, see [`Facebook\GraphNodes\GraphNodeFactory::makeGraphEvent()`](https://github.com/facebook/php-graph-sdk/blob/master/src/Facebook/GraphNodes/GraphNodeFactory.php#L158-L168).
> Fix: Remove useless override

- src/Facebook/FacebookBatchResponse.php
- src/Facebook/GraphNodes/GraphUser.php
> Fix: Provide more specific docblock

- tests/FacebookTestCredentials.php.dist
> Fix: Apply PSR-2 to credentials template

- composer.json
This PR
💁‍♂️ While `|` is also supported, the documentation suggests to use `||`. For reference, see https://getcomposer.org/doc/articles/versions.md#range.
> Fix: Use double pipe for specifying alternate PHP versions

- composer.json
This PR
Follows 7009ef8bc0415c6da9df1c13ede668b4a6e7b970.
💁‍♂️ Because why would we still use an older version if we can use a newer one? For reference, also see https://github.com/sebastianbergmann/phpunit/compare/4.8.30...5.7.5.
> Enhancement: Require latest version of phpunit/phpunit

- composer.json
This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.
> Enhancement: Keep packages sorted without specifying --sort-packages

- src/Facebook/FacebookRequest.php
It's called from the constructor which clearly allows null (in its phpdoc)
> FacebookRequest:setAccessToken(): phpdoc update: accepts null as an argument

- .travis.yml
- tests/PseudoRandomString/McryptPseudoRandomStringGeneratorTest.php
I have added 7.1 to Travis build and marked the mcrypt random string test as skipped for >=7.1 because it will never be returned anyway (check https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorFactory.php#L80).
> Add PHP 7.1 to Travis build

- docs/examples/batch_request.md
- docs/reference/Facebook.md
- docs/reference/FacebookBatchRequest.md
- src/Facebook/Facebook.php
- src/Facebook/FacebookBatchRequest.php
- tests/FacebookBatchRequestTest.php
- tests/FacebookTest.php
I made an initial attempt to add full batch support without the BC breaks that #706 introduced. Awaiting review @yguedidi @SammyK . :) I will adjust the docs too in the following days. :)
> Add full batch support without BC breaks

- src/Facebook/SignedRequest.php
PhpDoc expects @return, @returns was being used instead
This fixes #757
> Fix phpdoc @return instead of @returns

- src/Facebook/Exceptions/FacebookResponseException.php
https://developers.facebook.com/docs/graph-api/advanced/rate-limiting
At the end of this page you see list of rate limiting code.
I keep code "341" cause in an other page of the docs :
https://developers.facebook.com/docs/graph-api/using-graph-api#errors
We can see 341 code
> Add "new" API Throttle code

- tests/BatchResponseTest.php
- tests/FacebookTest.php
- tests/GraphNode/CollectionTest.php
- tests/GraphNode/GraphAchievementTest.php
- tests/RequestTest.php
I've refactored some tests, using:
- `assertContains` instead of `in_array` function;
- `assertCount` instead of `count` function;
- `assertInternalType`, avoiding using `is_*` functions;
- `assertArrayNotHasKey` instead of `isset` function;
> Refactoring tests

- src/Facebook/Helpers/FacebookRedirectLoginHelper.php
- tests/Fixtures/FooRedirectLoginOAuth2Client.php
- tests/Helpers/FacebookRedirectLoginHelperTest.php
This pull request fixes #877, since there hasn't been any activity in #905 for 25 days. 
I also adjusted the test to reflect the change and prevent accidental breaking in the future. 
I also changed the return value of `FooRedirectLoginOAuth2Client::getAccessTokenFromCode()` since that's the specified behavior in `OAuth2Client`. 
Please note that this fix is needed for “Strict Redirect URI Matching” which will be required by Facebook in March.
> Strip 'code' param

- src/GraphNode/GraphNode.php
- tests/FacebookTest.php
- tests/GraphNode/GraphEdgeTest.php
- tests/GraphNode/GraphNodeFactoryTest.php
- tests/GraphNode/GraphNodeTest.php
API design decision:
- A node **is not** a "collection of fields", it doesn't make sense to loop over them, count them, etc so all list behavior functions are removed. We care about accessing each specific field.
- We have the `getField()` function, so array access is not needed and less semantic.
As we want to provide as much typed node classes as possible with semantic getter for each field, the array access becomes even more useless.
Not having it will force use to maintain an updated types node API, which is goot IMO.
- Utility functions than were public to make their testing easier are now private, they are not part of what a graph node is.
Better review commit by commit :)
> Rework GraphNode API

- src/Facebook/GraphNodes/GraphPage.php
The GraphPage object was missing a get method for fan_count AKA page likes. So I added it.
> getFanCount() method to GraphPage. (get pagelikes)

- CHANGELOG.md
- src/Facebook/Exceptions/FacebookResponseException.php
- src/Facebook/Exceptions/FacebookResumableUploadException.php
- src/Facebook/FileUpload/FacebookResumableUploader.php
- src/Facebook/FileUpload/FacebookTransferChunk.php
- tests/FileUpload/FacebookResumableUploaderTest.php
- tests/Fixtures/FakeGraphApiForResumableUpload.php
Changed start_offset and end_offset from error code as written in documentation
> Fix resumable upload error "There was a problem uploading your video"
