facebook/php-graph-sdk

src/Facebook/Helpers/FacebookPageTabHelper.php

Removing per inline documentation to remove.

Removing deprecated method

---

src/Facebook/Exceptions/FacebookResponseException.php
src/Facebook/GraphNodes/GraphAlbum.php
src/Facebook/GraphNodes/GraphLocation.php
src/Facebook/GraphNodes/GraphObject.php
src/Facebook/GraphNodes/GraphObjectFactory.php
src/Facebook/GraphNodes/GraphPage.php
src/Facebook/GraphNodes/GraphSessionInfo.php
src/Facebook/GraphNodes/GraphUser.php
src/Facebook/Helpers/FacebookCanvasHelper.php
src/Facebook/Helpers/FacebookJavaScriptHelper.php
src/Facebook/Helpers/FacebookRedirectLoginHelper.php
src/Facebook/autoload.php
tests/FacebookBatchRequestTest.php
tests/FacebookClientTest.php
tests/FacebookRequestTest.php
tests/FacebookTest.php
tests/Helpers/FacebookRedirectLoginHelperTest.php

Cleaning up some of the code style items on @SammyK list https://github.com/SammyK/facebook-php-sdk-v4/issues/1

Code cleanup

---

src/Facebook/Helpers/FacebookSignedRequestFromInputHelper.php
tests/Helpers/FacebookSignedRequestFromInputHelperTest.php

Per https://github.com/SammyK/facebook-php-sdk-v4/issues/1

Remove unused code

---

README.md

Let's brag about our tests passing! :)

[4.1] Add travis-ci badge

---

src/Facebook/FacebookRedirectLoginHelper.php

I'm not sure if it's the proper way to do it, but I need to force authentication for users using my app. This does the job, based on https://developers.facebook.com/docs/facebook-login/reauthentication?locale=fr_FR
Thanks in advance for considering it.

allow to force re-authenticate with getLoginUrl method

---

src/Facebook/FacebookRedirectLoginHelper.php

- add missing php doc
- fix the case when you pass any value (eg `"foo"`)
@vrcAlbert sorry for being late to review your PR.. :/

Enhance #325

---

src/Facebook/PseudoRandomString/McryptPseudoRandomStringGenerator.php
src/Facebook/PseudoRandomString/OpenSslPseudoRandomStringGenerator.php
src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorInterface.php
src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorTrait.php
src/Facebook/PseudoRandomString/UrandomPseudoRandomStringGenerator.php

Bringing Facbebook\PseudiRandomString namespace into PSR2 compliance

---

src/Facebook/PersistentData/FacebookMemoryPersistentDataHandler.php
src/Facebook/PersistentData/FacebookSessionPersistentDataHandler.php
src/Facebook/PersistentData/PersistentDataInterface.php

Bringing Facbebook\PersistentData namespace into PSR2 compliance

---

src/Facebook/Facebook.php

Reformatted error message for PseudoRandomStringGeneratorInterface

---

tests/FacebookTest.php

from Chicago PHP Open Source workshop.

fixed enviroment variable false positive

---

src/Facebook/FacebookRequest.php

Bumps the default Graph version to the latest v2.3.

[4.0] Graph version bump to v2.3

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docs/sdk_downloads.fbmd
docs/sdk_getting_started.fbmd
docs/sdk_landing_page.fbmd
docs/sdk_reference.fbmd
phpunit.xml.dist
src/Facebook/Facebook.php
src/Facebook/autoload.php

Based on our new marketing schema. :)

Update 4.1 docs to refer to version 5

---

docs/GraphObject.fbmd
src/Facebook/FacebookResponse.php
src/Facebook/GraphNodes/GraphCoverPhoto.php
src/Facebook/GraphNodes/GraphEvent.php
src/Facebook/GraphNodes/GraphObjectFactory.php
tests/GraphNodes/GraphEventTest.php

Including the docs and tests of GraphEvent

Add GraphEvent and GraphCoverPhoto support

---

docs/GraphNode.fbmd
src/Facebook/FacebookResponse.php
src/Facebook/GraphNodes/GraphEvent.php
src/Facebook/GraphNodes/GraphGroup.php
src/Facebook/GraphNodes/GraphNodeFactory.php
tests/GraphNodes/GraphGroupTest.php

including the docs and the test class

Add GraphGroup support

---

tests/FacebookSessionTest.php

Wrong number of scopes in test

---

docs/GraphObject.fbmd

Fix typo in docs code

---

src/Facebook/Entities/SignedRequest.php

- doctrine/annotations is unhappy with @returns

Normalize php documentation in SignedRequest.php

---

tests/FacebookRedirectLoginHelperTest.php

Fix: Remove unused import

---

docs/Facebook.fbmd
docs/FacebookApp.fbmd
docs/FacebookFile.fbmd
docs/FacebookRedirectLoginHelper.fbmd
docs/FacebookResponseException.fbmd
docs/FacebookVideo.fbmd
docs/GraphNode.fbmd
docs/PersistentDataInterface.fbmd
docs/example_facebook_login.fbmd
docs/sdk_downloads.fbmd
docs/sdk_getting_started.fbmd
docs/sdk_landing_page.fbmd
docs/sdk_reference.fbmd

Formatting updates and changes (and more could be made to make them look better.)

Updates made during load to developers.facebook.com

---

README.md
docs/Facebook.fbmd
src/Facebook/Facebook.php

[Graph v2.4 is out](https://developers.facebook.com/docs/apps/changelog/)! :)

Upgrade references to Graph v2.4

---

src/Facebook/GraphNodes/GraphObjectFactory.php

Fix: Add missing import

---

src/Facebook/GraphNodes/Collection.php
tests/GraphNodes/CollectionTest.php

Make default field value return exact value

---

src/Facebook/FacebookResponse.php

fix typo in docblock

---

src/Facebook/GraphNodes/GraphUser.php

just adding a helper to fetch the graph user's email address, if any

added a getEmail() method for GraphUser objects

---

docs/Facebook.fbmd
docs/FacebookFile.fbmd
docs/FacebookVideo.fbmd
docs/example_upload_video.fbmd

The docs for the resumable upload feature. :)

Update docs to include resumable upload feature

---

src/Facebook/Authentication/AccessTokenMetadata.php

https://developers.facebook.com/bugs/917959338271504/

Don't convert a 0 timestamp, to support non-expiring tokens.

---

README.md
docs/Facebook.fbmd
docs/FacebookRequest.fbmd
docs/example_access_token_from_canvas.fbmd
docs/example_access_token_from_javascript.fbmd
docs/example_access_token_from_page_tab.fbmd
docs/example_batch_request.fbmd
docs/example_batch_upload.fbmd
docs/example_facebook_login.fbmd
docs/example_pagination_basic.fbmd
docs/example_post_links.fbmd
docs/example_retrieve_user_profile.fbmd
docs/example_upload_photo.fbmd
docs/example_upload_video.fbmd
docs/sdk_getting_started.fbmd
src/Facebook/Facebook.php
src/Facebook/GraphNodes/GraphAchievement.php

Graph [v2.5](https://developers.facebook.com/docs/apps/changelog) is out. :)

Update Graph version to v2.5

---

.travis.yml

Adds the PSR2 check using travis-ci and phpcs.
A [php-cs-fixer](http://cs.sensiolabs.org/) configuration could also be added to speed up the PSR alignment, should I add it to this PR?

Added PSR2 check to Travis CI

---

docs/sdk_getting_started.fbmd

In line with my edit in the repo, this ensures the use of the best option to install new dependencies, by running with as little side effects as possible and requiring only a single action.

Updating Composer install instructions

---

.gitignore
src/Facebook/Url/FacebookUrlDetectionHandler.php

@SammyK @yguedidi If you can review/comment/improve that would be great.
We got a report that x_forwarded_host could be used maliciously (in non-reverse-proxy situations)

Updating logic for x_forwarded_host

---

src/Facebook/autoload.php
src/Facebook/polyfills.php
tests/FacebookTest.php
tests/HttpClients/FacebookStreamHttpClientTest.php

Reverts some changes to #599 so that we can just get the bug fixed. :)

Finishes off #599

---

README.md

Change `new Facebook\Facebook` to `new Facebook` to fix error 'Fatal error: Class 'Facebook\Facebook\Facebook' not found...'.

Update README.md, correctly reference Facebook Class

---

README.md

Adds the fully qualified name to all references in the README.

Finishes off #581

---

CHANGELOG.md
src/Facebook/Facebook.php

Bump Graph API version to v2.7

---

src/Facebook/autoload.php

Ooops! Don't know how I missed this one. :/ Thanks Geoff Dawson for contacting me via email about this one! :)

Fix bug with including polyfills.php

---

src/Facebook/GraphNodes/GraphPage.php

add cover and picture type, graphobjectMap and methode

add cover and picture type and methode

---

composer.json

Fix the composer master branch alias for 6.0

---

README.md

In case there are new security issues we don't want to have publicly exposed via the issues. I put my email but if @yguedidi wants to be the contact, I'm totally cool with it! :)

Add "Security Vulnerabilities" section to README

---

src/Facebook/GraphNodes/GraphEdge.php
tests/GraphNodes/GraphEdgeTest.php

Aims to fix https://github.com/facebook/php-graph-sdk/issues/714

Fix map implementation in GraphEdge class.

---

tests/Authentication/OAuth2ClientTest.php
tests/FacebookRequestTest.php
tests/GraphNodes/CollectionTest.php
tests/Helpers/FacebookRedirectLoginHelperTest.php

Fix: Use more appropriate assertions

---

src/Facebook/FileUpload/Mimetypes.php

Add MIME type for SRT files

---

src/Facebook/FacebookRequest.php

https://github.com/facebook/php-graph-sdk/pull/639#issuecomment-288016523

FacebookRequest:setAccessToken(): accepts null as an argument

---

src/Facebook/GraphNodes/GraphNode.php

Added stop_time to the shouldCastAsDateTime whitelist array

---

docs/reference/GraphNode.md

Wrong method call documentation

---

docs/reference/GraphNode.md

Fix documentation #789

---

src/Facebook/GraphNodes/GraphUser.php

getBirthday () return Birthday type

Fix PHPDoc return type #857

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docs/getting_started.md
docs/reference.md
docs/reference/FacebookRedirectLoginHelper.md
docs/reference/FacebookRequest.md
docs/reference/FacebookResponseException.md
docs/reference/GraphNode.md

I've cleaned up our documentation, by removing whitespaces spaces and extra lines :smile:

Clean up documentation files
